#!/usr/bin/env bash

deno(){
  subshell "$@"
# /bin/deno "$@"
}

# deno --version

if [[ "$1" == cache ]]; then
  until
    deno run --unstable --import-map=import_map.json cache.ts --compat --cache-only
  do
    :
  done
  # patch
  grep -r "${DENO_DIR:-$HOME/.cache/deno}" -e 'function warn(pre, all, fmt) {' | cut -d : -f 1 | xargs sed -i -e 's/^function warn(pre, all, fmt) {$/function warn(pre, all, fmt) { return;/g'
  deno run --unstable --import-map=import_map.json cache.ts --compat --lock-write --lock=lock.json
else
  deno repl --unstable --eval-file=init.ts --import-map=import_map.json --no-check --compat # --lock=lock.json # # --lock-write
fi
