#!/usr/bin/env bash

if [[ "$1" == cache ]]; then
  until deno cache --unstable cache.ts --import-map=import_map.json --lock=lock.json; do sleep 1; done
  deno run --unstable --import-map=import_map.json --lock=lock.json cache.ts
elif [[ "$1" == lock ]]; then
  deno repl --unstable --eval-file=init.ts --import-map=import_map.json --no-check --lock=lock.json --lock-write # --compat
else
  deno repl --unstable --eval-file=init.ts --import-map=import_map.json --no-check --lock=lock.json # --compat # --lock-write 
fi
